#server.contextPath=/account-service
server:
  port: 8082
logging:
  level:
    org: INFO

#endpoints.cors.allowed-origins=*

management:
  security:
    enabled: false

#spring.mvc.view.prefix= /WEB-INF/jsp/
#spring.mvc.view.suffix= .jsp

security:
  basic:
    enabled: false

###
# Data Source Configuration
###
# Hibernate
spring:
  mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:3306/umoja_auth?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


consumer:
 createAccountQueue: registerCreateAccountQueue
 createAccountRoutingKey : account.created

gateway:
  url: http://localhost:8090/#

---

spring:
  profiles: docker
  mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://mysql-server:3306/umoja_auth?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
