logging:
  level:
    org.springframework.security: INFO

security.basic.enabled: false

# JPA
spring.jpa.hibernate.ddl-auto: none

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    
appfrontend:
  url: https://www.upayafrica.com

icbapp:
  url: icbapp.com

protocole:
  url: https

accounting:
  url: http://accounting-service
