logging:
  level:
    org.springframework.security: INFO

security.basic.enabled: false

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    
appfrontend:
  url: https://www.upayafrica.com
