#server.contextPath=/messaging-service
server:
  port: 8109
logging:
  level:
    org: INFO

#endpoints.cors.allowed-origins=*

management:
  security:
    enabled: false

#spring.mvc.view.prefix= /WEB-INF/jsp/
#spring.mvc.view.suffix= .jsp

security:
  basic:
    enabled: false
#  oauth2:
#    client:
#      clientId: server
#      clientSecret: trusted_server
#      accessTokenUri: http://localhost:8080/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server



###
# Data Source Configuration
###
# Hibernate
spring:
  mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:3306/umoja_messaging?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


consumer:
 queue: emailQueue
 routingKey : register.created

gateway:
  url: http://localhost:8090/#
