
#server.contextPath=/teller-transactions-test-service
server:
  port: 80


#endpoints.cors.allowed-origins=*

management:
  security:
    enabled: false

#spring.mvc.view.prefix= /WEB-INF/jsp/
#spring.mvc.view.suffix= .jsp

security:
  basic:
    enabled: false

###
# Data Source Configuration
###
# Hibernate
spring:
  mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://mysql_server:3306/${MYSQL_DATABASE_NAME}?useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_USER_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    
consumer:
 rpcGetAccountBalanceQueue: rpcGetAccountBalanceQueue
 rpcGetAccountBalanceRoutingKey : rpcGetAccountBalanceRoutingKey
 automateOpenBranchQueue: automateOpenBranchQueue
 automateOpenBranchRoutingKey : automateOpenBranchRoutingKey
